<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ccadeeb9c5c8',
	'title' => 'Hero',
	'fields' => array(
		array(
			'key' => 'field_5ccadef063cbd',
			'label' => 'Hero Image',
			'name' => 'sos_hero_image',
			'type' => 'image',
			'instructions' => 'Upload custom hero',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'sos-hero',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'hero-size',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg, jpeg, gif',
		),
		array(
			'key' => 'field_5ccaec1359d3d',
			'label' => 'Title',
			'name' => 'title',
			'type' => 'text',
			'instructions' => 'title of the page',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ccaec3459d3e',
			'label' => 'sub title',
			'name' => 'sub_title',
			'type' => 'text',
			'instructions' => 'enter the text you want below the title here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ccaf19f1dd7e',
			'label' => 'button',
			'name' => 'button',
			'type' => 'link',
			'instructions' => 'Enter the text for the Hero button',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'btn btn-info',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5ccaf2311dd7f',
			'label' => '',
			'name' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ccad6870c8c8',
	'title' => 'Information About The Dog',
	'fields' => array(
		array(
			'key' => 'field_5ccad6cfc2a6b',
			'label' => 'Born',
			'name' => 'born',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'birthday',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5ccad75dc2a6c',
			'label' => 'withers',
			'name' => 'withers',
			'type' => 'number',
			'instructions' => 'Tell us how big the dog is from paw to back',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'dog-withers',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'enter length here',
			'prepend' => '',
			'append' => 'cm',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5ccad864c2a6d',
			'label' => 'weight',
			'name' => 'weight',
			'type' => 'number',
			'instructions' => 'Tell us how much your dog weights in kilos',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'dog-weight',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'enter numbers above 0 here,',
			'prepend' => '',
			'append' => 'kg',
			'min' => 0,
			'max' => 999,
			'step' => '',
		),
		array(
			'key' => 'field_5ccad8ffc2a6e',
			'label' => 'adopted',
			'name' => 'adopted',
			'type' => 'date_picker',
			'instructions' => 'enter if the dog is available for adoption or if he or she is adopted.
if empty the dog is still available.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'adopted',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5cd287f241db8',
			'label' => 'gender',
			'name' => 'gender',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'male' => 'Male',
				'female' => 'Female',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sos_dogs',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cce81e10438b',
	'title' => 'Success Rating',
	'fields' => array(
		array(
			'key' => 'field_5cce81f5ecb1e',
			'label' => 'Rating',
			'name' => 'rating',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'rating',
			),
			'default_value' => 0,
			'min' => '',
			'max' => 5,
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'sos_success',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5cd297671badd',
	'title' => 'Theme Setting',
	'fields' => array(
		array(
			'key' => 'field_5cd2977de6a19',
			'label' => 'dogs shown on frontpage',
			'name' => 'dogs_shown_on_frontpage',
			'type' => 'number',
			'instructions' => 'enter the number of dogs you want to show on the frontpage.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 3,
			'placeholder' => 'enter number',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 10,
			'step' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
